FROM openjdk:latest
COPY build/libs/spring-security-example-0.0.1-SNAPSHOT.jar spring-security-example-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/spring-security-example-0.0.1-SNAPSHOT.jar"]
